name: Build and Deploy Angular App - Development

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app with dev config
        run: npm run build -- --configuration=dev

      - name: Deploy to Azure Web App (Development)
        uses: azure/webapps-deploy@v2
        with:
          app-name: kadevapp11            # replace with actual App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          package: ./dist/env-demo-angular              # replace if your output path is different
